@echo off
ECHO Started Audio Convert Script 1

SET AUDIO_CONVERT_EXECUTABLE=%1
SET TARGET_FOLDER=%2
SET SOURCE_AUDIO_FILE=%3

ECHO %AUDIO_CONVERT_EXECUTABLE%

%AUDIO_CONVERT_EXECUTABLE% -clear
%AUDIO_CONVERT_EXECUTABLE% -convert -outfolder "%TARGET_FOLDER%" %SOURCE_AUDIO_FILE% -format .mp3  -overwrite ALWAYS -settings .mp3 CBR 128 TRUE FORCE TRUE
exit